GOOGLE_API_KEY = "AIzaSyArYL462t5kvtV0QJ3cvKk_WcqVU8QLMWs"
GEMINI_API_KEY= "AIzaSyBTUgq4I1dwK6bMg3PXSFC2wdT8jy1khBs"
OPENAI_API_KEY_ORG = "sk-proj-FwDO31ssjngmL2sCRKPPT3BlbkFJseiYDH08rQddrmSRm67i"
REPLICATE_API_TOKEN="r8_MLw7bQ7wnizTesneuszfvbHNoGdh4pU1i5TfZ"


