GOOGLE_API_KEY = "AIzaSyArYL462t5kvtV0QJ3cvKk_WcqVU8QLMWs"
GEMINI_API_KEY= "AIzaSyBTUgq4I1dwK6bMg3PXSFC2wdT8jy1khBs"
OPENAI_API_KEY_ORG = "sk-proj-bG1PEybFMmbTi9s4POMKT3BlbkFJVSbGAU8T53ELazsU0tzv"
REPLICATE_API_TOKEN="r8_MLw7bQ7wnizTesneuszfvbHNoGdh4pU1i5TfZ"




